name: Setup MySQL Databases using Python Web Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ] 
    
jobs:
  setup-mysql:
    runs-on: ubuntu-latest
    steps:
    - name: Install MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-server
    - name: Start MySQL Service
      run: | 
        sudo service mysql start          
        sudo service mysql status
    - name: Show Databases
      run: |
        mysql -h localhost --port 3306 -uroot -proot -e "SHOW DATABASES";
        mysql -h localhost -uroot -proot -e "CREATE DATABASE IF NOT EXISTS Santhosh;"
        mysql -h localhost --port 3306 -uroot -proot -e "SHOW DATABASES";
        mysql -h localhost --port 3306 -uroot -proot -e "USE Santhosh; SHOW DATABASES;"
    
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install django
        pip3 install mysqlclient
        pip install Flask mysql-connector-python      
        sudo chmod 777 /var/run/mysqld/mysqld.sock
        mysql -h localhost --port 3306 -uroot -proot -e "SHOW DATABASES";
        python3 manage.py runserver
