name: Setup MySQL Databases using Python Web Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ] 
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip3 install django
        pip3 install mysqlclient
    - name: Flask\
      run: |
        python3 manage.py runserver
