name: Python Web Application with Database

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-server 
      
    - name: Start MySQL Service
      run: | 
          sudo service mysql start
          sudo service mysql status  
          
    - name: Database Create
      run: |
          mysql -h localhost --port 3306 -uroot -proot -e "SHOW DATABASES";
          mysql -h localhost -uroot -proot -e "CREATE DATABASE IF NOT EXISTS Murugan;"
          mysql -h localhost --port 3306 -uroot -proot -e "SHOW DATABASES";
          mysql -h localhost --port 3306 -uroot -proot -e "USE Murugan; SHOW DATABASES;"
          
    - name: Database Create
      run: |    
          pip3 install django
          pip3 install mysqlclient
          python3 manage.py makemigrations
          python manage.py migrate
          python3 manage.py runserver
          mysql -h localhost --port 3306 -uroot -proot -e "SHOW DATABASES";
                
                
        
