name: Build and Push Docker Image to DOckerhub

on:
  push:
    branches:
      - master

env:
    DOCKER_BUILD_VERSION: ${{ github.run_number }}

jobs:
  setup-mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Install MySQL
        run: sudo apt-get update && sudo apt-get install -y mysql-server

      - name: Start MySQL Service
        run: | 
          sudo service mysql start
          sudo service mysql status
      - name: Show Databases
        run: |
          mysql -h localhost --port 3306 -uroot -proot -e "SHOW DATABASES";
          mysql -h localhost -uroot -proot -e "CREATE DATABASE IF NOT EXISTS Santhosh;"
          mysql -h localhost --port 3306 -uroot -proot -e "SHOW DATABASES";
          mysql -h localhost --port 3306 -uroot -proot -e "USE Santhosh; SHOW DATABASES;"
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/register:${{ github.run_number }} .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/register:${{ github.run_number }}          
          
